language: python
python:
- "3.5"
- "3.6"
- "3.7"
dist: xenial
sudo: true
install:
- pip install marshmallow requests-oauthlib requests
- pip install --pre pylint astroid
- pip install pytest
script:
- pylint toodledo
- pytest -k test_get_account
